export enum LOCALE_PARSE_EVENTS {
  START = 'LOCALE_PARSE_START',
  PARSED = 'LOCALE_PARSE_PARSED'
}

export enum SOURCE_PARSE_EVENTS {
  START = 'SOURCE_PARSE_START',
  PARSED = 'SOURCE_PARSE_PARSED'
}
